# 🐳 Docker Compose - Complete Development Environment
# This file creates a full development stack with one command

version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: mongodb-ai-hub-db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mongodb-ai-hub
    volumes:
      - mongodb_data:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - ai-hub-network

  # Redis (for caching and sessions)
  redis:
    image: redis:7-alpine
    container_name: mongodb-ai-hub-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ai-hub-network

  # MongoDB AI Hub Application
  app:
    build: .
    container_name: mongodb-ai-hub-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://admin:password@mongodb:27017/mongodb-ai-hub?authSource=admin
      REDIS_URL: redis://redis:6379
      JWT_SECRET: dev-secret-change-in-production
      JWT_REFRESH_SECRET: dev-refresh-secret-change-in-production
      PORT: 3000
    depends_on:
      - mongodb
      - redis
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - ai-hub-network
    command: npm run dev

  # MongoDB Compass Alternative - Mongo Express (Web UI)
  mongo-express:
    image: mongo-express
    container_name: mongodb-ai-hub-admin
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongodb
    networks:
      - ai-hub-network

volumes:
  mongodb_data:
  redis_data:

networks:
  ai-hub-network:
    driver: bridge